CREATE TABLE cl_district (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

INSERT INTO cl_district (id, name) VALUES 
(1, 'ANENII NOI'), 
(2, 'BALTI'), 
(3, 'BASARABEASCA'),
(4, 'BRICENI'), 
(5, 'CAHUL'), 
(6, 'CALARASI'),
(7, 'CANTEMIR'), 
(8, 'CAUSENI'), 
(9, 'CHISINAU'),
(10, 'CIMISLIA'), 
(11, 'CRIULENI'), 
(12, 'DONDUSENI'),
(13, 'DROCHIA'), 
(14, 'DUBASARI'), 
(15, 'EDINET'),
(16, 'FALESTI'), 
(17, 'FLORESTI'), 
(18, 'GLODENI'),
(19, 'HINCESTI'), 
(20, 'IALOVENI'), 
(21, 'LEOVA'),
(22, 'NISPORENI'), 
(23, 'OCNITA'), 
(24, 'ORHEI'),
(25, 'REZINA'), 
(26, 'RISCANI'), 
(27, 'SINGEREI'),
(28, 'SOLDANESTI'), 
(29, 'SOROCA'), 
(30, 'STEFAN-VODA'),
(31, 'STRASENI'), 
(32, 'TARACLIA'), 
(33, 'TELENESTI'),
(34, 'UNGHENI'), 
(35, 'UTA GAGAUZIA'),
(36, 'TRANSNISTRIA');
